spring:
  profiles:
    active: default
#local, dev, prod 공통 설정
server.port: 8090    
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
       

####HTML 한글깨짐을 고칠수가 없었다.
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8   
#    additional-tld-skip-patterns: '*.jar'  #xml-apis.jar   그래들 익세션 문제 예외 https://stackoverflow.com/questions/44606914/embedded-tomcat-giving-failed-to-scan-jars-from-classloader-hierarchy
spring.mandatory-file-encoding: UTF-8
####HTML 한글깨짐을 고칠수가 없었다.

logging:
  config: classpath:logback-spring.xml 
  
logging.level:
  org.zalando.logbook: TRACE
  org.springframework.web.client: DEBUG   #restTemplate에서 로그 남기기

#메뉴, 프로그램 리스트 캐싱
spring.cache.ehcache.config: classpath:ehcache.xml  

#스프링액츄에이터 ==> 모니터링 프로그램
#spring.boot.admin:
#        client:
#          url: http://localhost:8081 
#          # username: jijs #admin monitoring server 의 id    
#          #password: admin #admin monitoring server 의 password 
#          instance: 
#            name: demoWeb #(어플리케이션 명) 
#            metadata: # 나의 어플리케이션 (스프링 시큐리티 )로그인 정보 
#              username: jijs           #내가 기본 security 기능을 끄고 ajax로 해서 인지를 못하는 듯하다.
#              userpassword: amdin      #로그인 부분은 순수하게 spring security 로 변경하자
#              
#actuator 라고 되어있지만 잘모르겠음  https://mycup.tistory.com/311
#spring.security: 
#    user: 
#      name: admin 
#      password: 1

#spring.boot.admin.client.auto-registration: true
# 어드민에서 모니터링 가능 하도록 엔드포인트도 모두 열어 줄것 
#management:
#  endpoints: 
#    web: 
#      exposure: 
#        include: '*' 
#  endpoint: 
#    health: 
#      show-details: always
#    shutdown.enabled: true


##출처: https://engkimbs.tistory.com/849 [새로비]
##oauth 용
spring.security: 
    oauth2: 
      client: 
        registration: 
          google: 
            client-id: 1013284899874-j55po4375ob25rpr8u0db0gvab4p3uod.apps.googleusercontent.com
            client-secret: 6Tr9hiMs9uKCjUHrO9bxv0lL 
          facebook: 
            client-id: 680106585392054 
            client-secret: da2b31555054ab973800eb26b38e3426 

custom: 
  oauth2: 
    kakao: 
      client-id: 19cf5b6db028ad395b915ddf55c256f4  ##rest api키
      client-secret: RNsvKAj3suFVj4mq3m1U0dsGFjTcd8Iz   ##카카오 로그인>보안>client secret 키
    naver: 
      client-id: vGcwBDQyZraIizRdgFqy 
      client-secret: g0pxjLs7mR
env:
  serverfilepath: c:\avdbs.com
  apiurl: http://localhost:8091/api/


--- #local 환경 
spring: 
  profiles: default 
  servlet:      
    multipart:
      file-size-threshold: 1MB    #1M이하면 메모리에 
      location: C:/Temp           #1M이상이면 이경로에 이걸 안해주면  System.getProperty("java.io.tmpdir"); 
      max-file-size: 100MB
      max-request-size: 100MB
server.servlet.session.timeout: 30m         #세션 만료시간 30분  30s 는 30초  
logging: 
  level: 
    root: debug 

