version: '3'

services:
  demojpa:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stockweb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=POSTGRES
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  demoweb:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplesecret
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8090:8090"
    command: 
      - python manage.py runserver 0:8000
    volumes:
      - ./:/app/